execute sentinel rotation script in the sentinel sidecar container if it exists

diff --git a/argocd/app_plane/dev/manifests/omnistrate-sentinel-tls-rotation-job.yaml b/argocd/app_plane/dev/manifests/omnistrate-sentinel-tls-rotation-job.yaml
--- a/argocd/app_plane/dev/manifests/omnistrate-sentinel-tls-rotation-job.yaml
+++ b/argocd/app_plane/dev/manifests/omnistrate-sentinel-tls-rotation-job.yaml
@@ -162,12 +162,18 @@ data:
         echo "Pod $POD_NAME is not running (status: $POD_STATUS), skipping..."
         continue
       fi
+
+      # Check if there's a container called "*sentinel*" in the pod. If so, execute the cert rotation script there
+      CONTAINER_NAME=service
+      if $PODS | jq -e ".items[] | select(.metadata.name == \"$POD_NAME\") | .spec.containers[] | select(.name | contains(\"sentinel\"))" > /dev/null; then
+        CONTAINER_NAME=$(kubectl get pod -n $TARGET_NAMESPACE $POD_NAME -o jsonpath='{.spec.containers[?(@.name == "service")].name}')
+      fi
       
       # Check if the cert_rotate_sentinel.sh script exists
       echo "Checking if cert_rotate_sentinel.sh exists in /data directory of pod $POD_NAME"
-      if kubectl exec -n $TARGET_NAMESPACE $POD_NAME -c service -- test -f /data/cert_rotate_sentinel.sh; then
+      if kubectl exec -n $TARGET_NAMESPACE $POD_NAME -c $CONTAINER_NAME -- test -f /data/cert_rotate_sentinel.sh; then
         echo "Executing TLS certificate rotation on pod: $POD_NAME"
-        kubectl exec -n $TARGET_NAMESPACE $POD_NAME -c service -- sh -c "cd /data && ./cert_rotate_sentinel.sh" || { echo "TLS rotation failed in $POD_NAME" ; exit 1; }
+        kubectl exec -n $TARGET_NAMESPACE $POD_NAME -c $CONTAINER_NAME -- sh -c "cd /data && ./cert_rotate_sentinel.sh" || { echo "TLS rotation failed in $POD_NAME" ; exit 1; }
         echo "TLS rotation completed for pod: $POD_NAME"
       else
         echo "Warning: cert_rotate_sentinel.sh not found in /data directory of pod $POD_NAME, skipping..."
